### ISSUE TITLE
Install warnings/errors

### ISSUE THREAD

**Issue by ACharbonneau** [fair-research/deriva-flow-client#3]
when installing, I get pip warning/error

> deriva-flow-client amanda$ python --version
Python 3.6.7

Ran:
`git clone https://github.com/fair-research/deriva-flow-client.git`
`cd deriva-flow-client`
` pip install -e .`

Get lots of download/install output then:

> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

>We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

>botocore 1.19.15 requires urllib3<1.26,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.22 which is incompatible.
awscli 1.16.72 requires botocore==1.12.62, but you'll have botocore 1.19.15 which is incompatible.
awscli 1.16.72 requires colorama<=0.3.9,>=0.2.5, but you'll have colorama 0.4.4 which is incompatible.
awscli 1.16.72 requires s3transfer<0.2.0,>=0.1.12, but you'll have s3transfer 0.3.3 which is incompatible.
globus-automate-client 0.10.4 requires jsonschema<4.0.0,>=3.2.0, but you'll have jsonschema 2.6.0 which is incompatible.

**Comment by ACharbonneau** [comment]
If I try to run it anyway I get:

`amanda$ cfde run ../training-and-engagement/docs/CFDE-Internal-Training/ToySubmission/HMP__sample_C2M2_Level_0_bdbag.contents/file.tsv`

> Traceback (most recent call last):
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
>     ws.require(__requires__)
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (jsonschema 2.6.0 (/Users/amanda/miniconda3/lib/python3.6/site-packages), Requirement.parse('jsonschema<4.0.0,>=3.2.0'), {'globus-automate-client'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/amanda/miniconda3/bin/cfde", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
>     @_call_aside
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
>     f(*args, **kwargs)
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/Users/amanda/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'jsonschema<4.0.0,>=3.2.0' distribution was not found and is required by globus-automate-client

so the install really does fail :/

**Comment by ACharbonneau** [comment]
running `pip install -e . --use-feature=2020-resolver` instead partially fixes it:

blahblahblah installing things then:

> Building wheels for collected packages: pyrsistent
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp36-cp36m-macosx_10_7_x86_64.whl size=68155 sha256=3150768b7294a4950f4e319aa4009eaf46a43cbdb0e4d856658a5d4725219a44
  Stored in directory: /Users/amanda/Library/Caches/pip/wheels/34/13/19/294da8e11bce7e563afee51251b9fa878185e14f4b5caf00cb
Successfully built pyrsistent
Installing collected packages: urllib3, pyrsistent, jsonschema
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.22
    Uninstalling urllib3-1.22:
      Successfully uninstalled urllib3-1.22
  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 2.6.0
    Uninstalling jsonschema-2.6.0:
      Successfully uninstalled jsonschema-2.6.0
ERROR: mknotebooks 0.6.2 requires markdown>=3.3.2, but you'll have markdown 3.2.2 which is incompatible.
mknotebooks 0.6.2 requires nbconvert>=6.0.0, but you'll have nbconvert 5.4.1 which is incompatible.
Successfully installed jsonschema-3.2.0 pyrsistent-0.17.3 urllib3-1.25.11

**Comment by ACharbonneau** [comment]
With the feature resolver, my install now seems to run, not sure whether mknotebooks is a real requirement for this app. I get a permission error now, but that's expected since I'm not in the right globus group with this ID.

So, it looks like changing the resolver will fix this error at least up until the point of credential checking.

**Comment by jgaff** [comment]
This issue appears to be resolved in the latest version of the submission tool (with the latest version of `pip`, which now includes the new resolver).
If the installation is still not working, please reopen this issue.
